# Generated by Django 3.1.7 on 2021-04-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('raze', models.TextField()),
                ('damage', models.IntegerField()),
                ('weakness', models.TextField()),
            ],
        ),
    ]
