# Generated by Django 3.1.7 on 2021-05-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ent',
            name='damage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ent',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ent',
            name='raze',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ent',
            name='weakness',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='damage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
